// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjip4fiWALDFoWaR7LQgm-OC0WBAEVIgo',
    appId: '1:83471333923:web:51964a44b26158b06e0f96',
    messagingSenderId: '83471333923',
    projectId: 'e-commerce-d0a32',
    authDomain: 'e-commerce-d0a32.firebaseapp.com',
    storageBucket: 'e-commerce-d0a32.appspot.com',
    measurementId: 'G-0ZNB440Z2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZJY2utVTLouCJ6s5v_GIJFngQ_vF1Yw',
    appId: '1:83471333923:android:61e13131bbb0ca876e0f96',
    messagingSenderId: '83471333923',
    projectId: 'e-commerce-d0a32',
    storageBucket: 'e-commerce-d0a32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0srKR-qkDE-n1pSTJX0_oN9tp1HIAWg',
    appId: '1:83471333923:ios:cbf657a7ae0362626e0f96',
    messagingSenderId: '83471333923',
    projectId: 'e-commerce-d0a32',
    storageBucket: 'e-commerce-d0a32.appspot.com',
    iosClientId: '83471333923-ge4bekd87f4eu9mftbqpo3kitf05hcm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0srKR-qkDE-n1pSTJX0_oN9tp1HIAWg',
    appId: '1:83471333923:ios:cbf657a7ae0362626e0f96',
    messagingSenderId: '83471333923',
    projectId: 'e-commerce-d0a32',
    storageBucket: 'e-commerce-d0a32.appspot.com',
    iosClientId: '83471333923-ge4bekd87f4eu9mftbqpo3kitf05hcm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
